name: KRChatColors
description: 'ChatColor Chinese reloaded'
version: 0.0.1
author: Hykilpikonna, Heiwa
main: cc.moecraft.kr.chatcolors.ChatColors
commands:
  chatcolor:
    description: Choose your chat color